-- 1. Create the junction table for Many-to-Many relationship
CREATE TABLE IF NOT EXISTS item_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT REFERENCES items(id) ON DELETE CASCADE NOT NULL,
    category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE NOT NULL,
    UNIQUE(item_id, category_id)
);

-- 2. Migrate existing data: Copy current 1:1 relationships to the new table
-- This ensures we don't lose current category associations
INSERT INTO item_categories (item_id, category_id)
SELECT id, category_id FROM items
ON CONFLICT (item_id, category_id) DO NOTHING;

-- 3. Add 'type' column to categories to distinguish between 'system' (default) and 'user' (custom sets)
ALTER TABLE categories ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'system';

-- 4. (Optional but recommended) Index for performance
CREATE INDEX IF NOT EXISTS idx_item_categories_item_id ON item_categories(item_id);
CREATE INDEX IF NOT EXISTS idx_item_categories_category_id ON item_categories(category_id);

-- Note: We are NOT removing items.category_id immediately to maintain backward compatibility during transition,
-- but the application will primarily use item_categories going forward.
